/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package datasiswafajar;

import java.awt.*;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.EditorKit;
import javax.swing.text.html.HTMLEditorKit;


/**
 *
 * @author LENOVO PC
 */
public class laporanguru extends javax.swing.JFrame {
    Connection konek;
    public Statement kn;
    
    void koneksi(){
        try{
        Class.forName("com.mysql.jdbc.Driver");
        konek = DriverManager.getConnection("jdbc:mysql://localhost/datasiswa_fajar?user=root&password=");
        kn = konek.createStatement();
    }catch (Exception e) {
        JOptionPane.showMessageDialog(null,"koneksi gagal..");
        System.out.println(e.getMessage());
    }
}
    
    void cetak(){
        String html =
                "<h4><center>Laporan Data Guru</center></h4>"+
                "<table width ='90%' border='0' align='center'>"+
                "<tr>"
                        +"<td bgcolor='#CCCCC' align='center'><strong>Nip</strong></td>"
                        +"<td bgcolor='#CCCCC' align='center'><strong>Nama</strong></td>"
                        +"<td bgcolor='#CCCCC' align='center'><strong>Mapel</strong></td>"
        +"</tr>";
        try{
            koneksi();
            String sql = "Select * From guru";
            PreparedStatement stat =konek.prepareStatement(sql);
            ResultSet set = stat.executeQuery(sql);
            while(set.next()) {
                html = html + "<tr>"
                        +" <td bgcolor='#EEEEEE'>"+set.getString("nip")+"</td>"
                        +" <td bgcolor='#EEEEEE'>"+set.getString("nama")+"</td>"
                        +" <td bgcolor='#EEEEEE'>"+set.getString("mapel")+"</td>"
                        +"</tr>";
                       
            }
            EditorKit x = new HTMLEditorKit();
            tampilcetak.setEditorKit(x);
            tampilcetak.setText(html);
        
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
    }

    /**
     * Creates new form laporansiswa
     */
    public laporanguru() {
        initComponents();
        koneksi();
        cetak();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tampilcetak = new javax.swing.JEditorPane();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(tampilcetak);

        jButton1.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        jButton1.setText("tampilcetak");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            tampilcetak.print();
        }catch (PrinterException ex) {
            Logger.getLogger(laporanguru.class.getName()).log(Level.SEVERE,null,ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laporanguru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laporanguru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laporanguru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laporanguru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new laporanguru().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JEditorPane tampilcetak;
    // End of variables declaration//GEN-END:variables
}
